EL-2467 - Initial setup for the seed project
UXAspects/UXAspects-Seed pull request #1
Opened 2017-04-27 12:47 UTC by AlastairMcKee

2017-04-27 15:16 UTC, ashley-hunter requested changes

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/app.module.ts
> +import './wrappers/expand-input-wrapper/ux-input-expand-ng1.directive';
The folder name is expand-input and filename is input-expand - make these consistent with the directive selector

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/shared/content-header/content-header.component.html
> +        <li *ngFor="let title of titles">
Rename variables to something a bit more specific eg:

```typescript
<li *ngFor="let breadcrumb of breadcrumbs">
```

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/shared/left-navigation/left-navigation.component.ts
> +        document.body.classList.add("animate-navbar");
Just add this class to the body tag in index.html rather than doing it through typescript

2017-04-27 15:16 UTC, ashley-hunter commented on src/assets/js/script.js
> +(function(){
This file should be removed.

2017-04-27 15:16 UTC, ashley-hunter commented on src/assets/less/site.lessx
> +/*Your styles go here*/
Remove the x from the end of the file extension

2017-04-27 15:16 UTC, ashley-hunter commented on .gitignore
> +node_modules/
Add set up instructions to readme.md

2017-04-27 15:16 UTC, ashley-hunter commented on package.json
> +    "grunt": "^0.4.5",
Review these dependencies, we don't use most of them in this project so we shouldn't be installing them. For example, we don't use any grunt or babel stuff, copywebpackplugin isn't used, js-yaml, jshint-loader, ng-cache-loader, script-loader and possibly others. After you remove dependencies from this file delete your node modules folder, then run npm install and make sure everything still works as expected

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/components/samples/sample/sample.component.ts
> +
Remove this empty line for consistency with other components

2017-04-27 15:16 UTC, ashley-hunter commented on package.json
> +  "keywords": [
Add a scripts property here. This should have a start script that runs the webpack dev server. This way they can just run `npm start` in the console to get going after they have installed the node modules. This should be documented in the readme eg:

```json
"scripts": {
   "start": "webpack-dev-server"
}
```

2017-04-27 15:16 UTC, ashley-hunter commented on package.json
> +  "version": "1.4.0",
Version should probably be 1.0.0

2017-04-27 15:16 UTC, ashley-hunter commented on webpack.config.js
> +var CopyWebpackPlugin = require('copy-webpack-plugin');
Remove this as it isnt used

2017-04-27 15:16 UTC, ashley-hunter commented on .gitignore
> +bower_components/
Missing bower.json file, this needs to pull in all the dependencies such as jquery and ux-aspects library itself.

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/app.component.ts
> +        this.router.events.subscribe((evt) => {
This subscription isnt doing anything so it can be removed

2017-04-27 15:16 UTC, ashley-hunter commented on src/vendor.ts
> +// import only the required jquery ui functionality
Remove the commented out code

2017-04-27 15:16 UTC, ashley-hunter commented on src/index.html
> +  <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
Import these in vendor.ts rather than in html as build output will be incorrect otherwsie

2017-04-27 15:16 UTC, ashley-hunter commented on package.json
> +    "grunt-jekyll": "^0.4.4",
Missing "raw-loader" dependency and "less" dependency

2017-04-27 15:16 UTC, ashley-hunter commented on src/assets/less/site.lessx
> +/*Your styles go here*/
Also this file needs to be imported in main.ts as currently adding styles here does nothing

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/shared/left-navigation/left-navigation.component.ts
> +        Observable.fromEvent(window, 'resize').debounceTime(200).subscribe(this.onResize.bind(this));
This observable needs stored in an instance variable so we can unsubscribe when component is destroyed

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/shared/left-navigation/left-navigation.component.ts
> +        document.removeEventListener('resize');
Instead of this we should unsubscribe from the observable here

2017-04-27 15:16 UTC, ashley-hunter commented on src/vendor.ts
> +import './app/app.module';
This shouldnt be here as it is already being loaded in main.ts

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/app.component.ts
> +        this.router.initialNavigation();
This can then be moved to the constructor. Remove the oninit implementation and import and change router so it is not private as it no longer needs stored on the instance

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/shared/page-header/page-header.component.html
> +<div class="affix-container">
![image](https://cloud.githubusercontent.com/assets/20795331/25485535/3228310a-2b56-11e7-8631-c4081e5c4e33.png)

Something is a bit off with the help center icon. It is too far left and is blue

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/shared/page-header/page-header.component.ts
> +        while ((element = element.parentElement) && !element.classList.contains('navbar-static-top'));
We shouldnt need to do any of this, we should just be able to have a variable in here called 'expanded' and use [class.show-search]="expanded" as an attribute on the element that needs the class to be toggled. In the click event we should just change the value of the variable

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/components/samples/sample/sample.component.ts
> +    title: string;
This is never used in the view, so it can be removed or else needs put to use in the view

2017-04-27 15:16 UTC, ashley-hunter commented on src/app/shared/content-header/content-header.component.ts
> +import { Component } from '@angular/core';
This whole component can be greatly simplified:

```typescript
import { Component } from '@angular/core';
import { ActivatedRoute, Router, NavigationEnd, ActivatedRouteSnapshot } from "@angular/router";
import 'rxjs/add/operator/filter';

@Component({
    selector: 'my-content-header',
    templateUrl: './content-header.component.html'
})
export class ContentHeaderComponent {

    heading: string;
    breadcrumbs: string[] = [];

    constructor(router: Router) {

        router.events.filter(event => event instanceof NavigationEnd).subscribe((event) => {
            let activeRoute = this.getActiveRoute(router.routerState.snapshot.root);
            
            // get the heading from the deepest route
            this.heading = activeRoute.data.title;
            this.breadcrumbs = this.getBreadcrumbs(activeRoute);
        });
    }

    getActiveRoute(route: ActivatedRouteSnapshot) {
        let activeRoute = route;

        while (activeRoute.children.length !== 0) {
            activeRoute = activeRoute.firstChild;
        }

        return activeRoute;
    }

    getBreadcrumbs(route: ActivatedRouteSnapshot) {
        let breadcrumbs = [];
        
        // ignore the immediate route - start with parent
        route = route.parent;

        // go through each parent and get their titles
        while (route.parent) {
            if (route.data.title) {
                breadcrumbs.push(route.data.title);
            }

            route = route.parent;
        }

        return breadcrumbs.reverse();
    }
}
```

In app.module.ts simply add the title to route data:

```typescript
const APPROUTES: Routes = [
    {
        path: 'samples',
        data: {
            title: 'Sample'
        },
        children: [{
            path: 'sample',
            component: SampleComponent,
            data: {
                title: 'Sample 1'
            }
        }]
    },
    { path: '', redirectTo: '/samples/sample', pathMatch: 'full' },
    { path: '**', component: SampleComponent }
];
```

2017-04-28 13:15 UTC, AlastairMcKee commented on src/app/shared/page-header/page-header.component.html
> +<div class="affix-container">
This has been removed from the seed project as its not doing anything anyway. There is a fix in for 1.1.0 to remove the need for wrapping this component in future.

2017-04-28 13:46 UTC, AlastairMcKee commented
Made changes and updated the readme

2017-05-02 09:27 UTC, ashley-hunter requested changes

2017-05-02 09:27 UTC, ashley-hunter commented on README.md
> +* Run ```webpack```
Remove this line and the webpack dev server line. Replace with "Run `npm start`" as this will build and start the webserver for them

2017-05-02 09:27 UTC, ashley-hunter commented on .gitignore
> +.grunt/
Remove grunt and specrunner from this list as neither will ever appear in this project

2017-05-02 09:27 UTC, ashley-hunter commented on src/app/shared/left-navigation/left-navigation.component.ts
> +    toggleSideNavigationFn() {
Remove `fn` from the function name as this is not the general naming convention in typescript

2017-05-02 09:27 UTC, ashley-hunter commented on src/app/shared/page-header/page-header.component.ts
> +import { Component, ElementRef, Renderer2, AfterViewInit } from '@angular/core';
Remove renderer2 as we didnt use this in the end

2017-05-02 09:27 UTC, ashley-hunter commented on webpack.config.js
> +            use: ['raw-loader', 'less-loader']
We should run less files through the css-loader as well to process any images, fonts etc.. We will likely also need to include the to-string-loader or css-to-string-loader.

2017-05-02 09:27 UTC, ashley-hunter commented on src/app/wrappers/expand-input-wrapper/ux-expand-input-ng1.directive.ts
> +angular.module('app').directive('uxExpandInputNg1', function() {
When I click on the search icon and then click cancel, then click the search icon again, the search box doesnt show until I click the search icon another time

2017-05-03 14:07 UTC, AlastairMcKee commented
Made requested changes

2017-05-03 14:34 UTC, ashley-hunter approved these changes
Looks good

2017-05-03 14:34 UTC, merged